name: publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Check formatting
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Compile
        run: yarn compile

      - name: Test
        run: yarn test

      - name: Bundle
        run: yarn run pack

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage-final.json

      - name: Publish next
        run: |
          mkdir next
          cp -r lib next
          cp action.yml next
          cd next
          git init .
          git config user.email "che-bot@eclipse.org"
          git config user.name "Eclipse Che Bot"
          git checkout --orphan next
          git add ./*
          git commit -m "Publish next version $(date +'%Y-%m-%d')" -s
          git push -f "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/${{ github.repository }}.git" next
